[package]
name = "diceware"
version = "0.1.1"
authors = ["Vladimir Timofeenko <public@vtimofeenko.com>"]
license = "WTFPL"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chbs = "0.0.8"
clap = "~2.33.3"
